# Generated by Django 4.1.6 on 2023-05-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_giao_vien', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khoa', models.CharField(max_length=100)),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=100)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_sinh_vien', models.CharField(max_length=100)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lop')),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_hoc', models.CharField(max_length=100)),
                ('so_tin_chi', models.IntegerField()),
                ('giao_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.giaovien')),
            ],
        ),
        migrations.AddField(
            model_name='giaovien',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.khoa'),
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_chuyen_can', models.FloatField()),
                ('diem_giua_ki', models.FloatField()),
                ('diem_cuoi_ki', models.FloatField()),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.monhoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sinhvien')),
            ],
        ),
    ]
