# Generated by Django 4.1.6 on 2023-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_giaovien_user_sinhvien_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diem',
            name='diem_chuyen_can',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diem_cuoi_ki',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diem_giua_ki',
            field=models.FloatField(null=True),
        ),
    ]
