# Generated by Django 4.1.6 on 2023-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_diem_diem_chuyen_can_alter_diem_diem_cuoi_ki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diem',
            name='diem_chuyen_can',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diem_cuoi_ki',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='diem',
            name='diem_giua_ki',
            field=models.FloatField(default=0, null=True),
        ),
    ]
